name: health_metrics
version: "1.0.0"
config-version: 2

profile: health_metrics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  health_metrics:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table